/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.CreateContract;
import static BLL.QuanLyCuDanBLL.cmb_BLL;
import BLL.ThongTinCanHoBLL;
import static DAL.QuanLyCuDanDAL.dsCuDan;
import Entities.CuDan;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;


public class NhanVienGUI extends javax.swing.JFrame {

    /**
     * Creates new form testFrameGUI
     *
     * @throws java.sql.SQLException
     */
    public NhanVienGUI() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        //======================================================================
        //Begin TabQuanLyCuDan
        //======================================================================
        txtMacudan.setEditable(false);
        cmbGioitinh.setSelectedItem(null);
        //======================================================================
        //End TabQuanLyCuDan
        //======================================================================

        //======================================================================
        //Begin TabThongTinCanHo
        //======================================================================
        txtMacanho1.setEditable(false);
        txtGiacanho.setEditable(false);
        txtNgaygiaodich.setEditable(false);
        cmbMacudan.setEnabled(false);
        cmbMacudan.setSelectedItem("");
        cmbGioitinh1.setSelectedItem(null);
        cmbMacudan.setModel(cmb_BLL()); //Đưa mã cư dân lên comboBox
        cmbMacudan.setSelectedItem(null);
        cmbSophong.setModel(ThongTinCanHoBLL.SoPhong_BLL());
        //======================================================================
        //End TabThongTinCanHo
        //======================================================================
        try {
            DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();// đối tượng thao tác với ô trong table
            renderer.setHorizontalAlignment(JLabel.CENTER);// Căn giữa dữ liệu bảng
            
            BLL.ThongTinMuaBanBLL.HienThongTinMuaBan(tblThongTinMuaBan);
            tblThongTinMuaBan.setDefaultRenderer(Object.class, renderer);
            BLL.QuanLyCuDanBLL.HienThongTinCuDan(tblQuanLyCuDan);
            tblQuanLyCuDan.setDefaultRenderer(Object.class, renderer);
            BLL.ThongTinCanHoBLL.HienThongTinCanho(tblThongTinCanHo);
            tblThongTinCanHo.setDefaultRenderer(Object.class, renderer);
        } catch (Exception ex) {
            Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error in NhanVienGUI: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        tabNhanvien = new javax.swing.JTabbedPane();
        tabQuanlycudan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMacudan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTencudan = new javax.swing.JTextField();
        txtNgaysinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQuequan = new javax.swing.JTextField();
        txtSocmt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        cmbGioitinh = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        btnRefreshQLCD = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQuanLyCuDan = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        txtTimKiem1 = new javax.swing.JTextField();
        tabThongtincanho = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThongTinCanHo = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMacanho1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtGiacanho = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNgaygiaodich = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cmbMacudan = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txtTenkh = new javax.swing.JTextField();
        txtNgsinh = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtScmt = new javax.swing.JTextField();
        cmbGioitinh1 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        chkLacudan = new javax.swing.JCheckBox();
        btnInhopdong = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        btTim_CanHo = new javax.swing.JButton();
        cbbDienTich = new javax.swing.JComboBox<>();
        cbbGia = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cmbSophong = new javax.swing.JComboBox<>();
        btnRefreshTTCH = new javax.swing.JButton();
        tabThongtinmuaban = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongTinMuaBan = new javax.swing.JTable();
        btnRefreshTTMB = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý chung cư");
        setBackground(new java.awt.Color(102, 255, 204));
        setName("frmNhanVien"); // NOI18N
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 81));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhân viên");

        btnLogout.setBackground(new java.awt.Color(153, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        btnLogout.setToolTipText("Đăng xuất");
        btnLogout.setBorder(null);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(427, 427, 427)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 440, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnLogout)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel25.setBackground(new java.awt.Color(255, 204, 153));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/employee.png"))); // NOI18N
        jLabel25.setPreferredSize(new java.awt.Dimension(25, 25));

        tabNhanvien.setBackground(new java.awt.Color(102, 255, 204));
        tabNhanvien.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tabNhanvien.setPreferredSize(new java.awt.Dimension(1280, 640));

        tabQuanlycudan.setBackground(new java.awt.Color(153, 255, 255));
        tabQuanlycudan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 163, 0), 2));

        jPanel2.setBackground(new java.awt.Color(240, 255, 182));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Mã cư dân:");

        txtMacudan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtMacudan.setForeground(new java.awt.Color(255, 0, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("SĐT:");

        txtSdt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtSdt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSdtMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Tên cư dân:");

        txtTencudan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTencudan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTencudanMouseClicked(evt);
            }
        });

        txtNgaysinh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNgaysinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNgaysinhMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Ngày sinh:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Giới tính:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Quê quán:");

        txtQuequan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtQuequan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQuequanMouseClicked(evt);
            }
        });

        txtSocmt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtSocmt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSocmtMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Số CMND:");

        btnSua.setBackground(new java.awt.Color(240, 255, 182));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        btnSua.setToolTipText("Sửa thông tin cư dân");
        btnSua.setBorder(null);
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        cmbGioitinh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbGioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cmbGioitinh.setEditor(null);
        cmbGioitinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbGioitinhMouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 102, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Thông tin cư dân");

        btnRefreshQLCD.setBackground(new java.awt.Color(240, 255, 182));
        btnRefreshQLCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rotation.png"))); // NOI18N
        btnRefreshQLCD.setToolTipText("Tải lại");
        btnRefreshQLCD.setBorder(null);
        btnRefreshQLCD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefreshQLCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshQLCDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgaysinh)
                    .addComponent(txtMacudan, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(cmbGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTencudan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSocmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefreshQLCD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbGioitinh, txtMacudan, txtNgaysinh, txtQuequan, txtSdt, txtSocmt, txtTencudan});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMacudan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtQuequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTencudan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(txtSocmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(btnRefreshQLCD, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("QUẢN LÍ CƯ DÂN");

        tblQuanLyCuDan.setBackground(new java.awt.Color(153, 255, 153));
        tblQuanLyCuDan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblQuanLyCuDan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã cư dân", "Tên cư dân", "Ngày sinh", "Giới tính", "SĐT", "Số CMT", "Quê quán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQuanLyCuDan.setToolTipText("Bảng Thông tin cư dân");
        tblQuanLyCuDan.setRowHeight(20);
        tblQuanLyCuDan.setSelectionBackground(new java.awt.Color(255, 51, 51));
        tblQuanLyCuDan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanLyCuDanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblQuanLyCuDan);
        if (tblQuanLyCuDan.getColumnModel().getColumnCount() > 0) {
            tblQuanLyCuDan.getColumnModel().getColumn(0).setResizable(false);
            tblQuanLyCuDan.getColumnModel().getColumn(1).setResizable(false);
            tblQuanLyCuDan.getColumnModel().getColumn(2).setResizable(false);
            tblQuanLyCuDan.getColumnModel().getColumn(3).setResizable(false);
            tblQuanLyCuDan.getColumnModel().getColumn(4).setResizable(false);
            tblQuanLyCuDan.getColumnModel().getColumn(5).setResizable(false);
            tblQuanLyCuDan.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Tìm kiếm:");

        txtTimKiem1.setForeground(new java.awt.Color(0, 0, 255));
        txtTimKiem1.setToolTipText("Nhập thông tin cần tìm kiếm");
        txtTimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiem1ActionPerformed(evt);
            }
        });
        txtTimKiem1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiem1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout tabQuanlycudanLayout = new javax.swing.GroupLayout(tabQuanlycudan);
        tabQuanlycudan.setLayout(tabQuanlycudanLayout);
        tabQuanlycudanLayout.setHorizontalGroup(
            tabQuanlycudanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabQuanlycudanLayout.createSequentialGroup()
                .addContainerGap(455, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(422, 422, 422))
            .addGroup(tabQuanlycudanLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        tabQuanlycudanLayout.setVerticalGroup(
            tabQuanlycudanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabQuanlycudanLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabQuanlycudanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );

        tabNhanvien.addTab("Quản lý cư dân", tabQuanlycudan);

        tabThongtincanho.setBackground(new java.awt.Color(153, 255, 255));
        tabThongtincanho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 2));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("THÔNG TIN CĂN HỘ");

        tblThongTinCanHo.setBackground(new java.awt.Color(153, 255, 153));
        tblThongTinCanHo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 2, true));
        tblThongTinCanHo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblThongTinCanHo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã căn hộ", "Diện tích", "Giá", "Số phòng", "Tên khu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Long.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThongTinCanHo.setToolTipText("Bảng Thông tin căn hộ");
        tblThongTinCanHo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblThongTinCanHo.setRowHeight(20);
        tblThongTinCanHo.setSelectionBackground(new java.awt.Color(255, 51, 0));
        tblThongTinCanHo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinCanHoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblThongTinCanHo);
        if (tblThongTinCanHo.getColumnModel().getColumnCount() > 0) {
            tblThongTinCanHo.getColumnModel().getColumn(0).setResizable(false);
            tblThongTinCanHo.getColumnModel().getColumn(1).setResizable(false);
            tblThongTinCanHo.getColumnModel().getColumn(2).setResizable(false);
            tblThongTinCanHo.getColumnModel().getColumn(3).setResizable(false);
            tblThongTinCanHo.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel4.setBackground(new java.awt.Color(221, 255, 236));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 2));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(83, 58, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Hợp Đồng");

        jLabel14.setText("Mã căn hộ:");

        txtMacanho1.setForeground(new java.awt.Color(255, 0, 0));

        jLabel15.setText("Giá căn hộ:");

        txtGiacanho.setForeground(new java.awt.Color(255, 0, 0));

        jLabel16.setText("Ngày giao dịch:");

        txtNgaygiaodich.setForeground(new java.awt.Color(255, 0, 0));

        jLabel17.setText("Mã cư dân:");

        cmbMacudan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMacudanItemStateChanged(evt);
            }
        });

        jLabel18.setText("Tên khách hàng:");

        jLabel19.setText("Ngày sinh:");

        jLabel20.setText("Giới tính:");

        jLabel21.setText("SĐT:");

        jLabel22.setText("Địa chỉ:");

        jLabel23.setText("Số CMND:");

        cmbGioitinh1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cmbGioitinh1.setEditor(null);

        jPanel5.setBackground(new java.awt.Color(221, 255, 236));

        chkLacudan.setBackground(new java.awt.Color(221, 255, 236));
        chkLacudan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        chkLacudan.setForeground(new java.awt.Color(255, 0, 51));
        chkLacudan.setText("Là cư dân");
        chkLacudan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkLacudanMouseClicked(evt);
            }
        });
        jPanel5.add(chkLacudan);

        btnInhopdong.setBackground(new java.awt.Color(221, 255, 236));
        btnInhopdong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/printer.png"))); // NOI18N
        btnInhopdong.setToolTipText("In hợp đồng");
        btnInhopdong.setBorder(null);
        btnInhopdong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInhopdong.setPreferredSize(new java.awt.Dimension(121, 45));
        btnInhopdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInhopdongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel22))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtMacanho1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNgaygiaodich, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGiacanho, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbMacudan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNgsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtScmt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbGioitinh1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(btnInhopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtMacanho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtGiacanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNgaygiaodich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cmbMacudan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtNgsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cmbGioitinh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtScmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInhopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 153));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 204, 0)));
        jPanel12.setToolTipText("Thanh tìm kiếm");
        jPanel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel12.setPreferredSize(new java.awt.Dimension(578, 60));

        btTim_CanHo.setBackground(new java.awt.Color(255, 255, 153));
        btTim_CanHo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btTim_CanHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/find.png"))); // NOI18N
        btTim_CanHo.setToolTipText("Tìm");
        btTim_CanHo.setBorder(null);
        btTim_CanHo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btTim_CanHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTim_CanHoActionPerformed(evt);
            }
        });

        cbbDienTich.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbbDienTich.setForeground(new java.awt.Color(0, 0, 204));
        cbbDienTich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Từ 30m² - 40m²", "Từ 40m² - 50mm²", "Trên 50m²" }));

        cbbGia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbbGia.setForeground(new java.awt.Color(0, 0, 204));
        cbbGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dưới 1 tỷ", "Từ 1 tỷ - 2 tỷ", "Trên 2 tỷ", " " }));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Diện tích");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Giá");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Số phòng");

        cmbSophong.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbSophong.setForeground(new java.awt.Color(0, 0, 204));

        btnRefreshTTCH.setBackground(new java.awt.Color(255, 255, 153));
        btnRefreshTTCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rotation.png"))); // NOI18N
        btnRefreshTTCH.setToolTipText("Refresh");
        btnRefreshTTCH.setBorder(null);
        btnRefreshTTCH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefreshTTCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTTCHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbDienTich, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbGia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbSophong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addComponent(btTim_CanHo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnRefreshTTCH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jPanel12Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbbDienTich, cbbGia, cmbSophong});

        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSophong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btTim_CanHo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshTTCH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout tabThongtincanhoLayout = new javax.swing.GroupLayout(tabThongtincanho);
        tabThongtincanho.setLayout(tabThongtincanhoLayout);
        tabThongtincanhoLayout.setHorizontalGroup(
            tabThongtincanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabThongtincanhoLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 1166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(tabThongtincanhoLayout.createSequentialGroup()
                .addGroup(tabThongtincanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabThongtincanhoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabThongtincanhoLayout.setVerticalGroup(
            tabThongtincanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabThongtincanhoLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabThongtincanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)))
        );

        tabNhanvien.addTab("Thông tin căn hộ", tabThongtincanho);

        tabThongtinmuaban.setBackground(new java.awt.Color(153, 255, 255));
        tabThongtinmuaban.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 226));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 255));

        tblThongTinMuaBan.setBackground(new java.awt.Color(153, 255, 153));
        tblThongTinMuaBan.setBorder(new javax.swing.border.MatteBorder(null));
        tblThongTinMuaBan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblThongTinMuaBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hợp Đồng", "Tên Khách Hàng", "Mã Căn Hộ", "Mã Cư Dân", "Địa Chỉ KH", "Giá", "Ngày Giao Dịch"
            }
        ));
        tblThongTinMuaBan.setToolTipText("Bảng Thông tin mua bán");
        tblThongTinMuaBan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblThongTinMuaBan.setGridColor(new java.awt.Color(153, 153, 153));
        tblThongTinMuaBan.setRowHeight(20);
        tblThongTinMuaBan.setSelectionBackground(new java.awt.Color(255, 51, 0));
        jScrollPane1.setViewportView(tblThongTinMuaBan);

        btnRefreshTTMB.setBackground(new java.awt.Color(153, 255, 255));
        btnRefreshTTMB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rotation.png"))); // NOI18N
        btnRefreshTTMB.setToolTipText("Tải lại");
        btnRefreshTTMB.setBorder(null);
        btnRefreshTTMB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefreshTTMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTTMBActionPerformed(evt);
            }
        });

        txtTimKiem.setForeground(new java.awt.Color(0, 0, 255));
        txtTimKiem.setToolTipText("Nhập thông tin cần tìm kiếm");
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Tìm kiếm:");

        jLabel2.setBackground(new java.awt.Color(102, 255, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("THÔNG TIN MUA BÁN");

        javax.swing.GroupLayout tabThongtinmuabanLayout = new javax.swing.GroupLayout(tabThongtinmuaban);
        tabThongtinmuaban.setLayout(tabThongtinmuabanLayout);
        tabThongtinmuabanLayout.setHorizontalGroup(
            tabThongtinmuabanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabThongtinmuabanLayout.createSequentialGroup()
                .addContainerGap(446, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(btnRefreshTTMB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(313, 313, 313))
            .addGroup(tabThongtinmuabanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        tabThongtinmuabanLayout.setVerticalGroup(
            tabThongtinmuabanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabThongtinmuabanLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabThongtinmuabanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabThongtinmuabanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addComponent(btnRefreshTTMB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
        );

        tabNhanvien.addTab("Thông tin mua bán", tabThongtinmuaban);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1081, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(tabNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1234, 877);
    }// </editor-fold>//GEN-END:initComponents

    public void setTextFieldQLCD() {
        txtTencudan.setEditable(false);
        txtNgaysinh.setEditable(false);
        txtSdt.setEditable(false);
        txtQuequan.setEditable(false);
        txtSocmt.setEditable(false);
        cmbGioitinh.setEnabled(false);
    }

    private void tblQuanLyCuDanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanLyCuDanMouseClicked
        setTextFieldQLCD();
        int row = tblQuanLyCuDan.getSelectedRow();
        txtMacudan.setText(tblQuanLyCuDan.getValueAt(row, 0).toString());
        txtTencudan.setText(tblQuanLyCuDan.getValueAt(row, 1).toString());
        txtNgaysinh.setText(tblQuanLyCuDan.getValueAt(row, 2).toString());
        cmbGioitinh.setSelectedItem(tblQuanLyCuDan.getValueAt(row, 3).toString());
        txtSdt.setText(tblQuanLyCuDan.getValueAt(row, 4).toString());
        txtSocmt.setText(tblQuanLyCuDan.getValueAt(row, 5).toString());
        txtQuequan.setText(tblQuanLyCuDan.getValueAt(row, 6).toString());
    }//GEN-LAST:event_tblQuanLyCuDanMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            if (txtMacudan.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Chọn mã cư dân.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (txtTencudan.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Tên cư dân trống.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (txtNgaysinh.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Ngày sinh trống.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (!RegexExpression.checkDateTime(txtNgaysinh.getText())) {
                JOptionPane.showMessageDialog(null, "Nhập sai ngày sinh.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (txtSdt.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Số điện thoại trống.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (txtSocmt.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Số CMND trống.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (txtQuequan.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Quê quán trống.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (!RegexExpression.checkPhoneNumber(txtSdt.getText())) {
                JOptionPane.showMessageDialog(null, "SĐT phải gồm 10 số.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (!RegexExpression.checkID(txtSocmt.getText().trim())) {
                JOptionPane.showMessageDialog(null, "Số CMND gồm 9 hoặc 12 số.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                BLL.QuanLyCuDanBLL.updateCD_BLL(txtMacudan, txtTencudan, txtNgaysinh, cmbGioitinh, txtSdt, txtSocmt, txtQuequan);
                BLL.ThongTinMuaBanBLL.UpdateHD_BLL(txtQuequan.getText(), txtMacudan.getText(), txtTencudan.getText());
                BLL.QuanLyCuDanBLL.HienThongTinCuDan(tblQuanLyCuDan);
                JOptionPane.showMessageDialog(null, "Sửa thành công.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error in btnSua: " + ex.getMessage());
        } catch (ParseException ex) {
            Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtTencudanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTencudanMouseClicked
        txtTencudan.setEditable(true);
        txtTencudan.requestFocus();
    }//GEN-LAST:event_txtTencudanMouseClicked

    private void tblThongTinCanHoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinCanHoMouseClicked
        int row = tblThongTinCanHo.getSelectedRow();
        txtMacanho1.setText(tblThongTinCanHo.getValueAt(row, 0).toString());
        txtGiacanho.setText(tblThongTinCanHo.getValueAt(row, 2).toString());
        //get today
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate ld = LocalDate.now();
        txtNgaygiaodich.setText(dtf.format(ld));
    }//GEN-LAST:event_tblThongTinCanHoMouseClicked

    public void ClearTextTTCH() {
        cmbMacudan.setSelectedItem(null);
        cmbMacudan.setEnabled(false);
        txtTenkh.setText(null);
        txtTenkh.requestFocus();
        txtNgsinh.setText(null);
        cmbGioitinh1.setSelectedItem(null);
        txtSDT.setText(null);
        txtScmt.setText(null);
        txtDiachi.setText(null);
    }

    private void chkLacudanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkLacudanMouseClicked
        if (chkLacudan.isSelected()) {
            cmbMacudan.setEnabled(true);
            txtTenkh.setEditable(false);
            txtNgsinh.setEditable(false);
            cmbGioitinh1.setEnabled(false);
            txtSDT.setEditable(false);
            txtScmt.setEditable(false);
            txtDiachi.setEditable(false);
        } else {
            ClearTextTTCH();

            cmbMacudan.setEnabled(false);
            txtTenkh.setEditable(true);
            txtNgsinh.setEditable(true);
            cmbGioitinh1.setEnabled(true);
            txtSDT.setEditable(true);
            txtScmt.setEditable(true);
            txtDiachi.setEditable(true);
        }
    }//GEN-LAST:event_chkLacudanMouseClicked


    private void cmbMacudanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMacudanItemStateChanged
        try {
            List<CuDan> dsCuDan = dsCuDan();
            String mcd;
            if (chkLacudan.isSelected()) {
                mcd = cmbMacudan.getSelectedItem().toString();
                for (CuDan cd : dsCuDan) {
                    if (mcd.equals(cd.getMaCuDan())) {
                        txtTenkh.setText(cd.getTenCuDan());
                        txtNgsinh.setText(cd.getNgaySinh());
                        if (cd.isGioiTinh() == true) {
                            cmbGioitinh1.setSelectedIndex(0);
                        } else {
                            cmbGioitinh1.setSelectedIndex(1);
                        }
                        txtSDT.setText(cd.getSoDT());
                        txtScmt.setText(cd.getSoCMT());
                        txtDiachi.setText(cd.getQueQuan());
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbMacudanItemStateChanged

    private void btnRefreshTTMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTTMBActionPerformed
        try {
            txtTimKiem.setText(null);
            BLL.ThongTinMuaBanBLL.HienThongTinMuaBan(tblThongTinMuaBan);
        } catch (Exception ex) {
            Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRefreshTTMBActionPerformed

    private void btnRefreshQLCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshQLCDActionPerformed
        try {
            BLL.QuanLyCuDanBLL.HienThongTinCuDan(tblQuanLyCuDan);
            txtMacudan.setText(null);
            txtTencudan.setText(null);
            txtNgaysinh.setText(null);
            cmbGioitinh.setSelectedItem(null);
            txtSdt.setText(null);
            txtQuequan.setText(null);
            txtSocmt.setText(null);
            txtTimKiem1.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRefreshQLCDActionPerformed

    private void txtNgaysinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNgaysinhMouseClicked
        txtNgaysinh.setEditable(true);
        txtNgaysinh.requestFocus();
    }//GEN-LAST:event_txtNgaysinhMouseClicked

    private void txtSdtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSdtMouseClicked
        txtSdt.setEditable(true);
        txtSdt.requestFocus();
    }//GEN-LAST:event_txtSdtMouseClicked

    private void txtQuequanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuequanMouseClicked
       txtQuequan.setEditable(true);
       txtQuequan.requestFocus();
    }//GEN-LAST:event_txtQuequanMouseClicked

    private void txtSocmtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSocmtMouseClicked
       txtSocmt.setEditable(true);
       txtSocmt.requestFocus();
    }//GEN-LAST:event_txtSocmtMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        this.dispose();
        DangNhapUI dn = new DangNhapUI("Quản lý chung cư");
        dn.showWindow();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        try {
            BLL.ThongTinMuaBanBLL.TimKiem_BLL(tblThongTinMuaBan, txtTimKiem.getText());
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btTim_CanHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTim_CanHoActionPerformed
        try {
            float tuDienTich = 0;
            float denDienTich = 0;
            long tuGia = 0;
            long denGia = 0;
            int sophong = Integer.valueOf(cmbSophong.getSelectedItem().toString());
            switch (cbbDienTich.getSelectedIndex()) {
                case 0:
                    tuDienTich = 30;
                    denDienTich = 40;
                    break;
                case 1:
                    tuDienTich = 40;
                    denDienTich = 50;
                    break;
                default:
                    tuDienTich = 50;
            }

            switch (cbbGia.getSelectedIndex()) {
                case 0:
                    denGia = 1000000000;
                    break;
                case 1:
                    tuGia = 1000000000;
                    denGia = 2000000000;
                    break;
                default:
                    tuGia = 2000000000;
            }

            ThongTinCanHoBLL.TKThongTinCanho(tblThongTinCanHo, tuDienTich, denDienTich, tuGia, denGia, sophong);
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btTim_CanHoActionPerformed

    private void btnRefreshTTCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTTCHActionPerformed
        try {
            BLL.ThongTinCanHoBLL.HienThongTinCanho(tblThongTinCanHo);
            cmbMacudan.setModel(cmb_BLL());
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRefreshTTCHActionPerformed

    private void btnInhopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInhopdongActionPerformed
        try {
            if (txtMacanho1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Chọn căn hộ.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (txtTenkh.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Nhập tên khách hàng.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (txtNgsinh.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Nhập ngày sinh.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (!RegexExpression.checkDateTime(txtNgsinh.getText())) {
                JOptionPane.showMessageDialog(null, "Nhập sai ngày sinh.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (cmbGioitinh1.getSelectedItem().toString().equals("")) {
                JOptionPane.showMessageDialog(null, "Chọn giới tính.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (txtSDT.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Nhập số điện thoại.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (!RegexExpression.checkPhoneNumber(txtSDT.getText())) {
                JOptionPane.showMessageDialog(null, "Số điện thoại gồm 10 s.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (txtScmt.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Nhập số chứng minh nhân dân.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (!RegexExpression.checkID(txtScmt.getText().trim())) {
                JOptionPane.showMessageDialog(null, "Số chứng minh nhân dân gồm 9 hoặc 12 số.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (txtDiachi.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Nhập địa chỉ.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                List<CuDan> dsCuDan = dsCuDan();
                String mcd = "111111";
                String maHopDong = "";

                if (chkLacudan.isSelected()) {
                    mcd = cmbMacudan.getSelectedItem().toString();
                } else {
                    for (CuDan cd : dsCuDan) {
                        if (cd.getMaCuDan().equals(mcd)) {
                            mcd = String.valueOf(Integer.parseInt(mcd) + 1);
                        }
                    }
                    BLL.QuanLyCuDanBLL.insertCD_BLL(mcd, txtTenkh, txtNgsinh, cmbGioitinh1, txtSDT, txtScmt, txtDiachi);
                }
                maHopDong = txtMacanho1.getText() + mcd;
                BLL.ThongTinCanHoBLL.updateCH_BLL(txtMacanho1.getText(), mcd);
                BLL.ThongTinMuaBanBLL.insertHD_BLL(maHopDong, txtNgaygiaodich.getText(), txtDiachi.getText(), mcd, txtMacanho1.getText(),txtTenkh.getText());
                BLL.ThongTinCanHoBLL.HienThongTinCanho(tblThongTinCanHo);
                JOptionPane.showMessageDialog(null, "Thêm hợp đồng thành công.", "Thông tin", JOptionPane.INFORMATION_MESSAGE);

                CreateWordFile();
                Desktop.getDesktop().open(new File("Hợp đồng mua căn hộ chung cư HATECO.docx.docx"));
            }
        } catch (SQLException e) {
            System.out.println("Error in btnInhopdong: " + e.getMessage());
        } catch (HeadlessException e) {
            System.out.println("Many errors: " + e.getMessage());
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Khách hàng này chưa là cư dân.", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
        }catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Hợp đồng không tồn tại.", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInhopdongActionPerformed

    private void cmbGioitinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbGioitinhMouseClicked
        cmbGioitinh.setEnabled(true);
    }//GEN-LAST:event_cmbGioitinhMouseClicked

    private void txtTimKiem1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiem1KeyReleased
        try {
            BLL.QuanLyCuDanBLL.TimKiemCD_BLL(tblQuanLyCuDan, txtTimKiem1.getText());
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtTimKiem1KeyReleased

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTimKiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiem1ActionPerformed

    public void CreateWordFile() {
        try {
            CreateContract contract = new CreateContract();
            contract.CreateContract(txtTenkh.getText(), txtNgsinh.getText(), txtScmt.getText(), txtDiachi.getText(), txtSDT.getText());
        } catch (Exception ex) {
            Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new NhanVienGUI().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTim_CanHo;
    private javax.swing.JButton btnInhopdong;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefreshQLCD;
    private javax.swing.JButton btnRefreshTTCH;
    private javax.swing.JButton btnRefreshTTMB;
    private javax.swing.JButton btnSua;
    private javax.swing.JComboBox<String> cbbDienTich;
    private javax.swing.JComboBox<String> cbbGia;
    private javax.swing.JCheckBox chkLacudan;
    private javax.swing.JComboBox<String> cmbGioitinh;
    private javax.swing.JComboBox<String> cmbGioitinh1;
    private javax.swing.JComboBox<String> cmbMacudan;
    private javax.swing.JComboBox<String> cmbSophong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane tabNhanvien;
    private javax.swing.JPanel tabQuanlycudan;
    private javax.swing.JPanel tabThongtincanho;
    private javax.swing.JPanel tabThongtinmuaban;
    private javax.swing.JTable tblQuanLyCuDan;
    private javax.swing.JTable tblThongTinCanHo;
    private javax.swing.JTable tblThongTinMuaBan;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtGiacanho;
    private javax.swing.JTextField txtMacanho1;
    private javax.swing.JTextField txtMacudan;
    private javax.swing.JTextField txtNgaygiaodich;
    private javax.swing.JTextField txtNgaysinh;
    private javax.swing.JTextField txtNgsinh;
    private javax.swing.JTextField txtQuequan;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtScmt;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSocmt;
    private javax.swing.JTextField txtTencudan;
    private javax.swing.JTextField txtTenkh;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTimKiem1;
    // End of variables declaration//GEN-END:variables
}
